### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by ziyue-pan** [iamNCJ/ZJU-Tronclass-Courseware-Downloader#2]
用Violentmonkey配置脚本，今天发现下载不了课件了。没有那个下载键
[](url)
![image](https://user-images.githubusercontent.com/50222787/79094958-a6c3d700-7d8b-11ea-9e8c-613076e26ce0.png)

**Comment by iamNCJ** [comment]
试试tampermonkey？

**Comment by ziyue-pan** [comment]
有效

**Comment by iamNCJ** [comment]
可能violent monkey有些不一样的地方 暂时没有经历研究 欢迎PR
